import serial
import time
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QRadioButton, QButtonGroup, QPushButton
from PyQt5 import QtCore, QtGui, QtWidgets
from pprint import pprint
from PyQt5.QtGui import * 
from PyQt5.QtCore import *
from PIL import Image, ImageDraw


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 527)
        MainWindow.setStyleSheet("QWidget{background-color: rgb(21, 0, 74);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.connection = QtWidgets.QPushButton(self.centralwidget)
        self.connection.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.connection.setObjectName("connection")
        self.gridLayout.addWidget(self.connection, 0, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.tab_1.setFont(font)
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_4.setContentsMargins(8, -1, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.p27 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p27.sizePolicy().hasHeightForWidth())
        self.p27.setSizePolicy(sizePolicy)
        self.p27.setMinimumSize(QtCore.QSize(30, 30))
        self.p27.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p27.setText("")
        self.p27.setObjectName("p27")
        self.gridLayout_4.addWidget(self.p27, 3, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(30, 30))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 6, 1, 1)
        self.p16 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p16.sizePolicy().hasHeightForWidth())
        self.p16.setSizePolicy(sizePolicy)
        self.p16.setMinimumSize(QtCore.QSize(30, 30))
        self.p16.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p16.setText("")
        self.p16.setObjectName("p16")
        self.gridLayout_4.addWidget(self.p16, 2, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(30, 30))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 7, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(30, 30))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.p13 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p13.sizePolicy().hasHeightForWidth())
        self.p13.setSizePolicy(sizePolicy)
        self.p13.setMinimumSize(QtCore.QSize(30, 30))
        self.p13.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p13.setText("")
        self.p13.setObjectName("p13")
        self.gridLayout_4.addWidget(self.p13, 2, 3, 1, 1)
        self.p14 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p14.sizePolicy().hasHeightForWidth())
        self.p14.setSizePolicy(sizePolicy)
        self.p14.setMinimumSize(QtCore.QSize(30, 30))
        self.p14.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p14.setText("")
        self.p14.setObjectName("p14")
        self.gridLayout_4.addWidget(self.p14, 2, 4, 1, 1)
        self.p21 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p21.sizePolicy().hasHeightForWidth())
        self.p21.setSizePolicy(sizePolicy)
        self.p21.setMinimumSize(QtCore.QSize(30, 30))
        self.p21.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p21.setText("")
        self.p21.setObjectName("p21")
        self.gridLayout_4.addWidget(self.p21, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(30, 30))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(30, 30))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 8, 1, 1)
        self.p15 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p15.sizePolicy().hasHeightForWidth())
        self.p15.setSizePolicy(sizePolicy)
        self.p15.setMinimumSize(QtCore.QSize(30, 30))
        self.p15.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p15.setText("")
        self.p15.setObjectName("p15")
        self.gridLayout_4.addWidget(self.p15, 2, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(30, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(30, 30))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.p23 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p23.sizePolicy().hasHeightForWidth())
        self.p23.setSizePolicy(sizePolicy)
        self.p23.setMinimumSize(QtCore.QSize(30, 30))
        self.p23.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p23.setText("")
        self.p23.setObjectName("p23")
        self.gridLayout_4.addWidget(self.p23, 3, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(30, 30))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 4, 1, 1)
        self.p11 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p11.sizePolicy().hasHeightForWidth())
        self.p11.setSizePolicy(sizePolicy)
        self.p11.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.p11.setFont(font)
        self.p11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.p11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p11.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p11.setText("")
        self.p11.setAutoDefault(False)
        self.p11.setDefault(False)
        self.p11.setObjectName("p11")
        self.gridLayout_4.addWidget(self.p11, 2, 1, 1, 1)
        self.p25 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p25.sizePolicy().hasHeightForWidth())
        self.p25.setSizePolicy(sizePolicy)
        self.p25.setMinimumSize(QtCore.QSize(30, 30))
        self.p25.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p25.setText("")
        self.p25.setObjectName("p25")
        self.gridLayout_4.addWidget(self.p25, 3, 5, 1, 1)
        self.p26 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p26.sizePolicy().hasHeightForWidth())
        self.p26.setSizePolicy(sizePolicy)
        self.p26.setMinimumSize(QtCore.QSize(30, 30))
        self.p26.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p26.setText("")
        self.p26.setObjectName("p26")
        self.gridLayout_4.addWidget(self.p26, 3, 6, 1, 1)
        self.p24 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p24.sizePolicy().hasHeightForWidth())
        self.p24.setSizePolicy(sizePolicy)
        self.p24.setMinimumSize(QtCore.QSize(30, 30))
        self.p24.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p24.setText("")
        self.p24.setObjectName("p24")
        self.gridLayout_4.addWidget(self.p24, 3, 4, 1, 1)
        self.p17 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p17.sizePolicy().hasHeightForWidth())
        self.p17.setSizePolicy(sizePolicy)
        self.p17.setMinimumSize(QtCore.QSize(30, 30))
        self.p17.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p17.setText("")
        self.p17.setObjectName("p17")
        self.gridLayout_4.addWidget(self.p17, 2, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(30, 30))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 5, 1, 1)
        self.p18 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p18.sizePolicy().hasHeightForWidth())
        self.p18.setSizePolicy(sizePolicy)
        self.p18.setMinimumSize(QtCore.QSize(30, 30))
        self.p18.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p18.setText("")
        self.p18.setObjectName("p18")
        self.gridLayout_4.addWidget(self.p18, 2, 8, 1, 1)
        self.p22 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p22.sizePolicy().hasHeightForWidth())
        self.p22.setSizePolicy(sizePolicy)
        self.p22.setMinimumSize(QtCore.QSize(30, 30))
        self.p22.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p22.setText("")
        self.p22.setObjectName("p22")
        self.gridLayout_4.addWidget(self.p22, 3, 2, 1, 1)
        self.p12 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p12.sizePolicy().hasHeightForWidth())
        self.p12.setSizePolicy(sizePolicy)
        self.p12.setMinimumSize(QtCore.QSize(30, 30))
        self.p12.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p12.setText("")
        self.p12.setObjectName("p12")
        self.gridLayout_4.addWidget(self.p12, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(30, 30))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 1, 1, 1)
        self.p63 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p63.sizePolicy().hasHeightForWidth())
        self.p63.setSizePolicy(sizePolicy)
        self.p63.setMinimumSize(QtCore.QSize(30, 30))
        self.p63.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p63.setText("")
        self.p63.setObjectName("p63")
        self.gridLayout_4.addWidget(self.p63, 7, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(30, 30))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 4, 0, 1, 1)
        self.p37 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p37.sizePolicy().hasHeightForWidth())
        self.p37.setSizePolicy(sizePolicy)
        self.p37.setMinimumSize(QtCore.QSize(30, 30))
        self.p37.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p37.setText("")
        self.p37.setObjectName("p37")
        self.gridLayout_4.addWidget(self.p37, 4, 7, 1, 1)
        self.p35 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p35.sizePolicy().hasHeightForWidth())
        self.p35.setSizePolicy(sizePolicy)
        self.p35.setMinimumSize(QtCore.QSize(30, 30))
        self.p35.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p35.setText("")
        self.p35.setObjectName("p35")
        self.gridLayout_4.addWidget(self.p35, 4, 5, 1, 1)
        self.p41 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p41.sizePolicy().hasHeightForWidth())
        self.p41.setSizePolicy(sizePolicy)
        self.p41.setMinimumSize(QtCore.QSize(30, 30))
        self.p41.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p41.setText("")
        self.p41.setObjectName("p41")
        self.gridLayout_4.addWidget(self.p41, 5, 1, 1, 1)
        self.p43 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p43.sizePolicy().hasHeightForWidth())
        self.p43.setSizePolicy(sizePolicy)
        self.p43.setMinimumSize(QtCore.QSize(30, 30))
        self.p43.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p43.setText("")
        self.p43.setObjectName("p43")
        self.gridLayout_4.addWidget(self.p43, 5, 3, 1, 1)
        self.p51 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p51.sizePolicy().hasHeightForWidth())
        self.p51.setSizePolicy(sizePolicy)
        self.p51.setMinimumSize(QtCore.QSize(30, 30))
        self.p51.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p51.setText("")
        self.p51.setObjectName("p51")
        self.gridLayout_4.addWidget(self.p51, 6, 1, 1, 1)
        self.p52 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p52.sizePolicy().hasHeightForWidth())
        self.p52.setSizePolicy(sizePolicy)
        self.p52.setMinimumSize(QtCore.QSize(30, 30))
        self.p52.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p52.setText("")
        self.p52.setObjectName("p52")
        self.gridLayout_4.addWidget(self.p52, 6, 2, 1, 1)
        self.p46 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p46.sizePolicy().hasHeightForWidth())
        self.p46.setSizePolicy(sizePolicy)
        self.p46.setMinimumSize(QtCore.QSize(30, 30))
        self.p46.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p46.setText("")
        self.p46.setObjectName("p46")
        self.gridLayout_4.addWidget(self.p46, 5, 6, 1, 1)
        self.p33 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p33.sizePolicy().hasHeightForWidth())
        self.p33.setSizePolicy(sizePolicy)
        self.p33.setMinimumSize(QtCore.QSize(30, 30))
        self.p33.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p33.setText("")
        self.p33.setObjectName("p33")
        self.gridLayout_4.addWidget(self.p33, 4, 3, 1, 1)
        self.p38 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p38.sizePolicy().hasHeightForWidth())
        self.p38.setSizePolicy(sizePolicy)
        self.p38.setMinimumSize(QtCore.QSize(30, 30))
        self.p38.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p38.setText("")
        self.p38.setObjectName("p38")
        self.gridLayout_4.addWidget(self.p38, 4, 8, 1, 1)
        self.p45 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p45.sizePolicy().hasHeightForWidth())
        self.p45.setSizePolicy(sizePolicy)
        self.p45.setMinimumSize(QtCore.QSize(30, 30))
        self.p45.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p45.setText("")
        self.p45.setObjectName("p45")
        self.gridLayout_4.addWidget(self.p45, 5, 5, 1, 1)
        self.p34 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p34.sizePolicy().hasHeightForWidth())
        self.p34.setSizePolicy(sizePolicy)
        self.p34.setMinimumSize(QtCore.QSize(30, 30))
        self.p34.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p34.setText("")
        self.p34.setObjectName("p34")
        self.gridLayout_4.addWidget(self.p34, 4, 4, 1, 1)
        self.p36 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p36.sizePolicy().hasHeightForWidth())
        self.p36.setSizePolicy(sizePolicy)
        self.p36.setMinimumSize(QtCore.QSize(30, 30))
        self.p36.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p36.setText("")
        self.p36.setObjectName("p36")
        self.gridLayout_4.addWidget(self.p36, 4, 6, 1, 1)
        self.p48 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p48.sizePolicy().hasHeightForWidth())
        self.p48.setSizePolicy(sizePolicy)
        self.p48.setMinimumSize(QtCore.QSize(30, 30))
        self.p48.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p48.setText("")
        self.p48.setObjectName("p48")
        self.gridLayout_4.addWidget(self.p48, 5, 8, 1, 1)
        self.p54 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p54.sizePolicy().hasHeightForWidth())
        self.p54.setSizePolicy(sizePolicy)
        self.p54.setMinimumSize(QtCore.QSize(30, 30))
        self.p54.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p54.setText("")
        self.p54.setObjectName("p54")
        self.gridLayout_4.addWidget(self.p54, 6, 4, 1, 1)
        self.p32 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p32.sizePolicy().hasHeightForWidth())
        self.p32.setSizePolicy(sizePolicy)
        self.p32.setMinimumSize(QtCore.QSize(30, 30))
        self.p32.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p32.setText("")
        self.p32.setObjectName("p32")
        self.gridLayout_4.addWidget(self.p32, 4, 2, 1, 1)
        self.p42 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p42.sizePolicy().hasHeightForWidth())
        self.p42.setSizePolicy(sizePolicy)
        self.p42.setMinimumSize(QtCore.QSize(30, 30))
        self.p42.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p42.setText("")
        self.p42.setObjectName("p42")
        self.gridLayout_4.addWidget(self.p42, 5, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(30, 30))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(30, 30))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 5, 0, 1, 1)
        self.p44 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p44.sizePolicy().hasHeightForWidth())
        self.p44.setSizePolicy(sizePolicy)
        self.p44.setMinimumSize(QtCore.QSize(30, 30))
        self.p44.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p44.setText("")
        self.p44.setObjectName("p44")
        self.gridLayout_4.addWidget(self.p44, 5, 4, 1, 1)
        self.p55 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p55.sizePolicy().hasHeightForWidth())
        self.p55.setSizePolicy(sizePolicy)
        self.p55.setMinimumSize(QtCore.QSize(30, 30))
        self.p55.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p55.setText("")
        self.p55.setObjectName("p55")
        self.gridLayout_4.addWidget(self.p55, 6, 5, 1, 1)
        self.p53 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p53.sizePolicy().hasHeightForWidth())
        self.p53.setSizePolicy(sizePolicy)
        self.p53.setMinimumSize(QtCore.QSize(30, 30))
        self.p53.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p53.setText("")
        self.p53.setObjectName("p53")
        self.gridLayout_4.addWidget(self.p53, 6, 3, 1, 1)
        self.p57 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p57.sizePolicy().hasHeightForWidth())
        self.p57.setSizePolicy(sizePolicy)
        self.p57.setMinimumSize(QtCore.QSize(30, 30))
        self.p57.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p57.setText("")
        self.p57.setObjectName("p57")
        self.gridLayout_4.addWidget(self.p57, 6, 7, 1, 1)
        self.p31 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p31.sizePolicy().hasHeightForWidth())
        self.p31.setSizePolicy(sizePolicy)
        self.p31.setMinimumSize(QtCore.QSize(30, 30))
        self.p31.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p31.setText("")
        self.p31.setObjectName("p31")
        self.gridLayout_4.addWidget(self.p31, 4, 1, 1, 1)
        self.p58 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p58.sizePolicy().hasHeightForWidth())
        self.p58.setSizePolicy(sizePolicy)
        self.p58.setMinimumSize(QtCore.QSize(30, 30))
        self.p58.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p58.setText("")
        self.p58.setObjectName("p58")
        self.gridLayout_4.addWidget(self.p58, 6, 8, 1, 1)
        self.p61 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p61.sizePolicy().hasHeightForWidth())
        self.p61.setSizePolicy(sizePolicy)
        self.p61.setMinimumSize(QtCore.QSize(30, 30))
        self.p61.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p61.setText("")
        self.p61.setObjectName("p61")
        self.gridLayout_4.addWidget(self.p61, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(30, 30))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 7, 0, 1, 1)
        self.p62 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p62.sizePolicy().hasHeightForWidth())
        self.p62.setSizePolicy(sizePolicy)
        self.p62.setMinimumSize(QtCore.QSize(30, 30))
        self.p62.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p62.setText("")
        self.p62.setObjectName("p62")
        self.gridLayout_4.addWidget(self.p62, 7, 2, 1, 1)
        self.p47 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p47.sizePolicy().hasHeightForWidth())
        self.p47.setSizePolicy(sizePolicy)
        self.p47.setMinimumSize(QtCore.QSize(30, 30))
        self.p47.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p47.setText("")
        self.p47.setObjectName("p47")
        self.gridLayout_4.addWidget(self.p47, 5, 7, 1, 1)
        self.p56 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p56.sizePolicy().hasHeightForWidth())
        self.p56.setSizePolicy(sizePolicy)
        self.p56.setMinimumSize(QtCore.QSize(30, 30))
        self.p56.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p56.setText("")
        self.p56.setObjectName("p56")
        self.gridLayout_4.addWidget(self.p56, 6, 6, 1, 1)
        self.p28 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p28.sizePolicy().hasHeightForWidth())
        self.p28.setSizePolicy(sizePolicy)
        self.p28.setMinimumSize(QtCore.QSize(30, 30))
        self.p28.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p28.setText("")
        self.p28.setObjectName("p28")
        self.gridLayout_4.addWidget(self.p28, 3, 8, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(30, 30))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 8, 0, 1, 1)
        self.p71 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p71.sizePolicy().hasHeightForWidth())
        self.p71.setSizePolicy(sizePolicy)
        self.p71.setMinimumSize(QtCore.QSize(30, 30))
        self.p71.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p71.setText("")
        self.p71.setObjectName("p71")
        self.gridLayout_4.addWidget(self.p71, 8, 1, 1, 1)
        self.p73 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p73.sizePolicy().hasHeightForWidth())
        self.p73.setSizePolicy(sizePolicy)
        self.p73.setMinimumSize(QtCore.QSize(30, 30))
        self.p73.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p73.setText("")
        self.p73.setObjectName("p73")
        self.gridLayout_4.addWidget(self.p73, 8, 3, 1, 1)
        self.p75 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p75.sizePolicy().hasHeightForWidth())
        self.p75.setSizePolicy(sizePolicy)
        self.p75.setMinimumSize(QtCore.QSize(30, 30))
        self.p75.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p75.setText("")
        self.p75.setObjectName("p75")
        self.gridLayout_4.addWidget(self.p75, 8, 5, 1, 1)
        self.p85 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p85.sizePolicy().hasHeightForWidth())
        self.p85.setSizePolicy(sizePolicy)
        self.p85.setMinimumSize(QtCore.QSize(30, 30))
        self.p85.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p85.setText("")
        self.p85.setObjectName("p85")
        self.gridLayout_4.addWidget(self.p85, 9, 5, 1, 1)
        self.p87 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p87.sizePolicy().hasHeightForWidth())
        self.p87.setSizePolicy(sizePolicy)
        self.p87.setMinimumSize(QtCore.QSize(30, 30))
        self.p87.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p87.setText("")
        self.p87.setObjectName("p87")
        self.gridLayout_4.addWidget(self.p87, 9, 7, 1, 1)
        self.p72 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p72.sizePolicy().hasHeightForWidth())
        self.p72.setSizePolicy(sizePolicy)
        self.p72.setMinimumSize(QtCore.QSize(30, 30))
        self.p72.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p72.setText("")
        self.p72.setObjectName("p72")
        self.gridLayout_4.addWidget(self.p72, 8, 2, 1, 1)
        self.p66 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p66.sizePolicy().hasHeightForWidth())
        self.p66.setSizePolicy(sizePolicy)
        self.p66.setMinimumSize(QtCore.QSize(30, 30))
        self.p66.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p66.setText("")
        self.p66.setObjectName("p66")
        self.gridLayout_4.addWidget(self.p66, 7, 6, 1, 1)
        self.p88 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p88.sizePolicy().hasHeightForWidth())
        self.p88.setSizePolicy(sizePolicy)
        self.p88.setMinimumSize(QtCore.QSize(30, 30))
        self.p88.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p88.setText("")
        self.p88.setObjectName("p88")
        self.gridLayout_4.addWidget(self.p88, 9, 8, 1, 1)
        self.p68 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p68.sizePolicy().hasHeightForWidth())
        self.p68.setSizePolicy(sizePolicy)
        self.p68.setMinimumSize(QtCore.QSize(30, 30))
        self.p68.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p68.setText("")
        self.p68.setObjectName("p68")
        self.gridLayout_4.addWidget(self.p68, 7, 8, 1, 1)
        self.p65 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p65.sizePolicy().hasHeightForWidth())
        self.p65.setSizePolicy(sizePolicy)
        self.p65.setMinimumSize(QtCore.QSize(30, 30))
        self.p65.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p65.setText("")
        self.p65.setObjectName("p65")
        self.gridLayout_4.addWidget(self.p65, 7, 5, 1, 1)
        self.p67 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p67.sizePolicy().hasHeightForWidth())
        self.p67.setSizePolicy(sizePolicy)
        self.p67.setMinimumSize(QtCore.QSize(30, 30))
        self.p67.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p67.setText("")
        self.p67.setObjectName("p67")
        self.gridLayout_4.addWidget(self.p67, 7, 7, 1, 1)
        self.p77 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p77.sizePolicy().hasHeightForWidth())
        self.p77.setSizePolicy(sizePolicy)
        self.p77.setMinimumSize(QtCore.QSize(30, 30))
        self.p77.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p77.setText("")
        self.p77.setObjectName("p77")
        self.gridLayout_4.addWidget(self.p77, 8, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(30, 30))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 9, 0, 1, 1)
        self.p81 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p81.sizePolicy().hasHeightForWidth())
        self.p81.setSizePolicy(sizePolicy)
        self.p81.setMinimumSize(QtCore.QSize(30, 30))
        self.p81.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p81.setText("")
        self.p81.setObjectName("p81")
        self.gridLayout_4.addWidget(self.p81, 9, 1, 1, 1)
        self.p83 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p83.sizePolicy().hasHeightForWidth())
        self.p83.setSizePolicy(sizePolicy)
        self.p83.setMinimumSize(QtCore.QSize(30, 30))
        self.p83.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p83.setText("")
        self.p83.setObjectName("p83")
        self.gridLayout_4.addWidget(self.p83, 9, 3, 1, 1)
        self.p78 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p78.sizePolicy().hasHeightForWidth())
        self.p78.setSizePolicy(sizePolicy)
        self.p78.setMinimumSize(QtCore.QSize(30, 30))
        self.p78.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p78.setText("")
        self.p78.setObjectName("p78")
        self.gridLayout_4.addWidget(self.p78, 8, 8, 1, 1)
        self.p76 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p76.sizePolicy().hasHeightForWidth())
        self.p76.setSizePolicy(sizePolicy)
        self.p76.setMinimumSize(QtCore.QSize(30, 30))
        self.p76.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p76.setText("")
        self.p76.setObjectName("p76")
        self.gridLayout_4.addWidget(self.p76, 8, 6, 1, 1)
        self.p64 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p64.sizePolicy().hasHeightForWidth())
        self.p64.setSizePolicy(sizePolicy)
        self.p64.setMinimumSize(QtCore.QSize(30, 30))
        self.p64.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p64.setText("")
        self.p64.setObjectName("p64")
        self.gridLayout_4.addWidget(self.p64, 7, 4, 1, 1)
        self.p74 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p74.sizePolicy().hasHeightForWidth())
        self.p74.setSizePolicy(sizePolicy)
        self.p74.setMinimumSize(QtCore.QSize(30, 30))
        self.p74.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p74.setText("")
        self.p74.setObjectName("p74")
        self.gridLayout_4.addWidget(self.p74, 8, 4, 1, 1)
        self.p82 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p82.sizePolicy().hasHeightForWidth())
        self.p82.setSizePolicy(sizePolicy)
        self.p82.setMinimumSize(QtCore.QSize(30, 30))
        self.p82.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p82.setText("")
        self.p82.setObjectName("p82")
        self.gridLayout_4.addWidget(self.p82, 9, 2, 1, 1)
        self.p84 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p84.sizePolicy().hasHeightForWidth())
        self.p84.setSizePolicy(sizePolicy)
        self.p84.setMinimumSize(QtCore.QSize(30, 30))
        self.p84.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p84.setText("")
        self.p84.setObjectName("p84")
        self.gridLayout_4.addWidget(self.p84, 9, 4, 1, 1)
        self.p86 = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p86.sizePolicy().hasHeightForWidth())
        self.p86.setSizePolicy(sizePolicy)
        self.p86.setMinimumSize(QtCore.QSize(30, 30))
        self.p86.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.p86.setText("")
        self.p86.setObjectName("p86")
        self.gridLayout_4.addWidget(self.p86, 9, 6, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setStyleSheet("QToolButton{background-color: rgb(255, 255, 255);}")
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_4.addWidget(self.toolButton_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(165, 165))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(165, 165))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 1, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(165, 165))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_6.addWidget(self.pushButton_6, 3, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(165, 165))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(165, 165))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 3, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(165, 165))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_65 = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_65.sizePolicy().hasHeightForWidth())
        self.pushButton_65.setSizePolicy(sizePolicy)
        self.pushButton_65.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.pushButton_65.setObjectName("pushButton_65")
        self.gridLayout_5.addWidget(self.pushButton_65, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab_5)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 100))
        self.label_2.setStyleSheet("QLabel{background-color: rgb(255, 0, 0);}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 2, 2)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalSlider = QtWidgets.QSlider(self.widget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.verticalSlider.setFont(font)
        self.verticalSlider.setStyleSheet("")
        self.verticalSlider.setMaximum(255)
        self.verticalSlider.setSliderPosition(255)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout_3.addWidget(self.verticalSlider, 0, 0, 1, 1)
        self.verticalSlider_3 = QtWidgets.QSlider(self.widget_2)
        self.verticalSlider_3.setMaximum(255)
        self.verticalSlider_3.setProperty("value", 0)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.gridLayout_3.addWidget(self.verticalSlider_3, 0, 2, 1, 1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.widget_2)
        self.verticalSlider_2.setMaximum(255)
        self.verticalSlider_2.setProperty("value", 0)
        self.verticalSlider_2.setSliderPosition(0)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.gridLayout_3.addWidget(self.verticalSlider_2, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 2, 0, 1, 2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.gridLayout_2.addWidget(self.widget_3, 3, 0, 1, 2)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 5, 1)
        self.pushButton_66 = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_66.sizePolicy().hasHeightForWidth())
        self.pushButton_66.setSizePolicy(sizePolicy)
        self.pushButton_66.setStyleSheet("QPushButton{background-color: rgb(255, 255, 255);}")
        self.pushButton_66.setObjectName("pushButton_66")
        self.gridLayout_5.addWidget(self.pushButton_66, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(44)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(370, 370))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget, 6, 0, 1, 5)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 0, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connection.setText(_translate("MainWindow", "Подключить"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">6</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">7</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">1</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">3</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">8</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">2</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">2</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">4</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">5</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">1</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">3</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">5</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">4</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">6</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">7</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">8</span></p></body></html>"))
        self.toolButton_2.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "LED"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Example"))
        self.pushButton_65.setText(_translate("MainWindow", "Сохранить"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Red</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Green</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Blue</span></p></body></html>"))
        self.pushButton_66.setText(_translate("MainWindow", "Предпросмотр"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Export"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\"/></p></body></html>"))



class MyWidget(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle('PyQT LED Matrix')
        self.label_23.setText("")
        self.label_23.setStyleSheet("QLabel { color: rgba(255, 255, 255); }")

        self.matrix = [[self.p11, self.p12, self.p13, self.p14, self.p15, self.p16, self.p17, self.p18],
                  [self.p21, self.p22, self.p23, self.p24, self.p25, self.p26, self.p27, self.p28],
                  [self.p31, self.p32, self.p33, self.p34, self.p35, self.p36, self.p37, self.p38],
                  [self.p41, self.p42, self.p43, self.p44, self.p45, self.p46, self.p47, self.p48],
                  [self.p51, self.p52, self.p53, self.p54, self.p55, self.p56, self.p57, self.p58],
                  [self.p61, self.p62, self.p63, self.p64, self.p65, self.p66, self.p67, self.p68],
                  [self.p71, self.p72, self.p73, self.p74, self.p75, self.p76, self.p77, self.p78],
                  [self.p81, self.p82, self.p83, self.p84, self.p85, self.p86, self.p87, self.p88]]

        self.led_matrix = [[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]]
                  

        #self.tabWidget.setEnabled(False)
    
        self.r = 255
        self.g = 0
        self.b = 0
        self.state = 0

        self.verticalSlider.valueChanged.connect(lambda x: self.colour("r", self.verticalSlider.value()))
        self.verticalSlider_3.valueChanged.connect(lambda x: self.colour("g", self.verticalSlider_3.value()))
        self.verticalSlider_2.valueChanged.connect(lambda x: self.colour("b", self.verticalSlider_2.value()))

        self.connection.clicked.connect(self.connect_btn)
        self.toolButton_2.clicked.connect(self.clear)

        for index_y, i in enumerate(self.matrix):
            for index_x, n in enumerate(i):
                n.clicked.connect(self.matrix_colour)

        self.pushButton.setStyleSheet("background-image : url(full.jpg);")
        self.pushButton.clicked.connect(lambda x: self.ready_img("full"))
        
        self.pushButton_2.setStyleSheet("background-image : url(smile.jpg);")
        self.pushButton_2.clicked.connect(lambda x: self.ready_img("smile"))
        
        self.pushButton_5.setStyleSheet("background-image : url(heart.jpg);")
        self.pushButton_5.clicked.connect(lambda x: self.ready_img("heart"))
        
        self.pushButton_4.setStyleSheet("background-image : url(cat.jpg);")
        self.pushButton_4.clicked.connect(lambda x: self.ready_img("cat"))
        
        self.pushButton_3.setStyleSheet("background-image : url(apple.jpg);")
        self.pushButton_3.clicked.connect(lambda x: self.ready_img("apple"))
        
        self.pushButton_6.setStyleSheet("background-image : url(arrow.jpg);")
        self.pushButton_6.clicked.connect(lambda x: self.ready_img("arrow"))

        self.pushButton_66.clicked.connect(self.preview)

    def preview(self):
        im_orig = Image.open("full.jpg")
        im = Image.new("RGB", (400, 400), (255, 255, 255))
        draw = ImageDraw.Draw(im)

        for index_row, row in enumerate(self.led_matrix):
            for index_col, col in enumerate(row):
                if col == 1:
                    temp = 50 * index_col
                    temp2 = 50 * index_row
                    draw.ellipse((temp + 5, temp2 + 5, temp + 45, temp2 + 45), fill=(255, 0, 0))

        im.save("full.jpg")
        self.pixmap = QPixmap("full.jpg")
        self.label_21.setPixmap(self.pixmap)
        im_orig.save("full1.jpg")

    def ready_img(self, img):
        if img == "full":
            self.led_matrix = [[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],
                               [1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],
                               [1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],
                               [1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1]]
        elif img == "smile":
            self.led_matrix = [[0,0,0,0,0,0,0,0],[0,0,1,0,0,1,0,0],
                               [0,0,1,0,0,1,0,0],[0,0,1,0,0,1,0,0],
                               [0,0,0,0,0,0,0,0],[0,1,0,0,0,0,1,0],
                               [0,0,1,1,1,1,0,0],[0,0,0,0,0,0,0,0]]

        elif img == "heart":
            self.led_matrix = [[0,0,0,0,0,0,0,0],[0,1,1,0,0,1,1,0],
                               [1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],
                               [1,1,1,1,1,1,1,1],[0,1,1,1,1,1,1,0],
                               [0,0,1,1,1,1,0,0],[0,0,0,1,1,0,00]]

        elif img == "cat":
            self.led_matrix = [[0,0,0,1,0,0,0,1],[0,0,0,1,1,1,1,1],
                               [0,0,0,1,0,1,0,1],[1,0,0,0,1,1,1,0],
                               [1,0,0,0,0,1,0,0],[1,0,0,1,1,1,1,0],
                               [1,0,1,1,1,1,1,0],[1,1,1,1,1,1,1,1]]

        elif img == "apple":
            self.led_matrix = [[0,0,0,1,1,0,0,0],[0,0,0,0,1,0,0,0],
                               [0,1,1,1,0,1,1,0],[1,1,1,1,1,1,1,1],
                               [1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],
                               [0,1,1,1,1,1,1,0],[0,0,1,1,1,1,0,0]]

        else:
            self.led_matrix = [[0,0,0,1,1,0,0,0],[0,0,1,1,1,1,0,0],
                               [0,1,1,1,1,1,1,0],[1,1,1,1,1,1,1,1],
                               [0,0,0,1,1,0,0,0],[0,0,0,1,1,0,0,0],
                               [0,0,0,1,1,0,0,0],[0,0,0,1,1,0,0,0]]

    def clear(self):
        for index_y, i in enumerate(self.matrix):
            for index_x, n in enumerate(i):
                n.setStyleSheet("background-color: white")
                self.led_matrix[index_y][index_x] = 0

    def matrix_colour(self):
        sending_button = self.sender()
        sending_button = list(str(sending_button.objectName())[1:])
        if self.led_matrix[int(sending_button[0]) - 1][int(sending_button[1]) - 1] == 0:
            self.matrix[int(sending_button[0]) - 1][int(sending_button[1]) - 1].setStyleSheet("background-color: red")
            self.led_matrix[int(sending_button[0]) - 1][int(sending_button[1]) - 1] = 1
        else:
            self.matrix[int(sending_button[0]) - 1][int(sending_button[1]) - 1].setStyleSheet("background-color: white")
            self.led_matrix[int(sending_button[0]) - 1][int(sending_button[1]) - 1] = 0

    def colour(self, rgb, val):
        if rgb == "r":
            self.r = val
        elif rgb == "g":
            self.g = val
        else:
            self.b = val

        temp = "background-color: rgb({}, {}, {})".format(self.r, self.g, self.b)
        self.label_2.setStyleSheet(temp)

        send_data = rgb + str(val)

        #print(self.write_read(send_data)) 
        

    def connect_btn(self):
        if self.state == 0:
            try:
                self.arduino = serial.Serial(port='COM3', baudrate=115200, timeout=.1)
                self.state = 1
            except Exception:
                self.label_23.setText("Подключтье Arduino")
                self.connection.setStyleSheet("background-color: red")

            if self.state == 1:
                self.label_23.setText("")
                self.connection.setStyleSheet("background-color: green")
                self.connection.setText("Отключить")
                
        else:
            self.arduino.close()
            self.connection.setStyleSheet("background-color: white")
            self.connection.setText("Подключить")
            self.state = 0


    def write_read(self, x):
        self.arduino.write(bytes(x, 'utf-8'))
        time.sleep(0.05)
        return "done"
                

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.exit(app.exec_())

    





